# Build Stage
FROM node:12.19.0-alpine3.12 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
  # Also install development dependencies

# Deploy Stage
FROM node:12.19.0-alpine3.12 as development-stage
WORKDIR /app
COPY --from=build-stage /app /app
COPY . .

# Launch the application
CMD npm run dev